# Generated by Django 4.1.2 on 2022-11-14 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainApp", "0006_contact"),
    ]

    operations = [
        migrations.AddField(
            model_name="buyer", name="otp", field=models.IntegerField(default=-123234),
        ),
    ]
